--------------------------------------------------------------------------------
-- DS1_DDL.sql
-- Conectare: SALES (XEPDB1)
-- Scop: creează tabelele DS1 (ticketing / sales / payments / validations).
-- Re-runnable: încearcă să șteargă tabelele în ordinea corectă.
--------------------------------------------------------------------------------

BEGIN EXECUTE IMMEDIATE 'DROP TABLE ticket_validations CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE payments CASCADE CONSTRAINTS';          EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ticket_sales CASCADE CONSTRAINTS';      EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ticket_types CASCADE CONSTRAINTS';      EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE ticket_types (
  ticket_type_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_name        VARCHAR2(100) NOT NULL,
  base_price         NUMBER(10,2) NOT NULL,
  validity_minutes   NUMBER,
  validity_days      NUMBER,
  CONSTRAINT ck_ticket_validity CHECK (
    (validity_minutes IS NOT NULL AND validity_days IS NULL)
    OR
    (validity_minutes IS NULL AND validity_days IS NOT NULL)
  )
);

CREATE TABLE ticket_sales (
  order_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  city               VARCHAR2(50) DEFAULT 'Iasi' NOT NULL,
  zone               VARCHAR2(50) NOT NULL,
  customer_category  VARCHAR2(20) NOT NULL,
  amount_paid        NUMBER(10,2) NOT NULL,
  purchase_date      DATE NOT NULL,
  CONSTRAINT ck_customer_category CHECK (
    customer_category IN ('standard','elev','student','pensionar')
  )
);

CREATE TABLE payments (
  payment_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id           NUMBER NOT NULL,
  method             VARCHAR2(10) NOT NULL,
  status             VARCHAR2(10) NOT NULL,
  pay_ts             TIMESTAMP NOT NULL,
  CONSTRAINT fk_payments_order FOREIGN KEY (order_id) REFERENCES ticket_sales(order_id),
  CONSTRAINT ck_pay_method CHECK (method IN ('card','cash')),
  CONSTRAINT ck_pay_status CHECK (status IN ('paid','failed','refunded'))
);

CREATE TABLE ticket_validations (
  validation_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id           NUMBER NOT NULL,
  validation_ts      TIMESTAMP NOT NULL,
  ticket_type_id     NUMBER NOT NULL,
  line_id            VARCHAR2(20) NOT NULL,
  route_id           VARCHAR2(20) NOT NULL,
  stop_id            VARCHAR2(20) NOT NULL,
  vehicle_id         VARCHAR2(20) NOT NULL,
  CONSTRAINT fk_val_order FOREIGN KEY (order_id) REFERENCES ticket_sales(order_id),
  CONSTRAINT fk_val_type  FOREIGN KEY (ticket_type_id) REFERENCES ticket_types(ticket_type_id)
);

-- verificare
SELECT table_name
FROM user_tables
WHERE table_name IN ('TICKET_TYPES','TICKET_SALES','PAYMENTS','TICKET_VALIDATIONS')
ORDER BY table_name;